SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS BOARD_INFO;




/* Create Tables */

CREATE TABLE BOARD_INFO
(
	BI_NUM int(11) NOT NULL AUTO_INCREMENT,
	BI_TITLE varchar(300) NOT NULL,
	BI_CONTENT text NOT NULL,
	BI_CREDAT char(8) NOT NULL,
	BI_CRETIM char(6) NOT NULL,
	BI_LMODAT char(8) NOT NULL,
	BI_LMOTIM char(6) NOT NULL,
	BI_ACTIVE char(1) NOT NULL,
	BI_CNT int(11) NOT NULL,
	PRIMARY KEY (BI_NUM)
);



