SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS YES24;




/* Create Tables */

CREATE TABLE YES24
(
	Y_NUM int NOT NULL AUTO_INCREMENT,
	Y_IMG  NOT NULL,
	Y_TITLE varchar(20) NOT NULL,
	Y_AUTER varchar(10) NOT NULL,
	Y_URL char NOT NULL,
	Y_SUBTITLE varchar(100) NOT NULL,
	Y_PRICE int NOT NULL,
	Y_PUBLISHING varchar(10) NOT NULL,
	PRIMARY KEY (Y_NUM)
);



